# minimal values files for testing - enable just what you need and copy required values from staging environment

global:
  defaultNodePool: default-pool
  k8sOpsSecretName: ops
  k8sOpsImage: gcr.io/uumpa123/midburn-k8s
  environmentName: ori
  opsRepoSlug: Midburn/midburn-k8s
  opsRepoBranch: master
  googleProjectId: midbarrn
  projectName: midburn
  enableRootChart: false

traefik:
  enabled: false

spark:
  enabled: false

nginx:
  enabled: false

volunteers:
  enabled: false

profiles:
  enabled: true
  dbImportUrl: gs://midburn-k8s-backups/profiles-db-production-dump-2018-01-16-11-30.sql

bi:
  enabled: true
