{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: volunteersdb
spec:
  ports:
  - name: '27017'
    port: 27017
  selector:
    app: volunteersdb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: volunteersdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: volunteersdb
    spec:
      containers:
      - name: volunteersdb
        image: mongo
        command:
        - bash
        - "-c"
        - |
          rm -f /data/db/mongod.lock
          /usr/local/bin/docker-entrypoint.sh mongod &
          while true; do sleep 86400; done
        ports:
        - {containerPort: 27017}
        resources:
          requests: {cpu: 20m}
      {{ if .Values.persistentStorageName }}
        volumeMounts:
        - name: volunteersdb
          mountPath: /data/db
      volumes:
      - name: volunteersdb
        nfs:
          path: "/data/{{ .Values.global.environmentName }}/{{ .Values.persistentStorageName }}"
          server: {{ .Values.global.persistentStorageIP | quote }}
      {{ end }}
{{ end }}
