{{ if .Values.mysql.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:10.0
        ports:
        - {containerPort: 3306}
        resources:
          requests: {cpu: 20m}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
---
apiVersion: v1
kind: Service
metadata: {name: mysql}
spec:
  ports:
  - name: '3306'
    port: 3306
  selector: {app: mysql}
{{ end }}
