{{ if .Values.spark.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: {{ .Values.spark.image | quote }}
        ports:
        - {containerPort: 3000}
        resources:
          requests: {cpu: 20m}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
---
apiVersion: v1
kind: Service
metadata: {name: spark}
spec:
  ports:
  - name: '3000'
    port: 3000
  selector: {app: spark}
{{ end }}
